coverage:
  precision: 2
  round: nearest
  range: "50...90"
  status:
    project:
      default:
        target: "80%"
        threshold: "5%"
    patch:
      default:
        target: auto
        threshold: null
    changes:
      default:
        target: auto
